spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinetime_db
    username: root
    password: myroot@12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml # Location of Liquibase changelog file
  data:
    redis:
      connect-timeout: 5
      host: localhost
      port: 6379
      timeout: 5


  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 5


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

server:
  port: 8080

cinetime:
  theater:
    cache-ttl: 86400 # TTL for Redis cache in seconds (1 day)


